Repository mun-jihye/rolling-paper-app, pull requests merged in 2024-03, with the labels that each got.

#60 [#30] feat: ListPage UI 구현 완료, Card 컴포넌트에 Badge 추가, useDeviceType 커스텀 훅 생성
  public/index.html
  src/assets/images/landingPage/cardImg.png
  src/assets/images/landingPage/emojiImg.png
  src/components/commons/badges/EmojiBadge.jsx
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/Modal.jsx
  src/components/commons/toast/Toast.jsx
  src/hooks/useDeviceType.jsx
  src/pages/AddMessagePage.jsx
  src/pages/AddPostPage.jsx
  src/pages/LandingPage.jsx
  src/pages/ListPage.jsx
  src/pages/MessagePage.jsx
  src/pages/PostPage.jsx
Labels: enhancement

#61 [#30] feat: ListPage UI 구현 완료, Card 컴포넌트에 Badge 추가, useDeviceType 커스텀 훅 생성
  src/components/commons/badges/EmojiBadge.jsx
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/hooks/useDeviceType.jsx
  src/pages/ListPage.jsx
Labels: enhancement

#65 feat: mock data를 이용해 card component 구현 및 반응형 적용
  src/components/commons/Profile.jsx
  src/components/commons/badges/ProfileBadge.jsx
  src/components/commons/card/test
  src/components/commons/cards/CardMessage.jsx
  src/components/commons/cards/Date.jsx
  src/components/commons/cards/FromTitle.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/modal/Modal.jsx
  src/components/commons/modal/modal/Portal.jsx
  src/components/commons/modal/modal/index.js
  src/components/edit/CardContainer.jsx
  src/components/edit/EditContainer.jsx
  src/components/edit/FromCard.jsx
  src/components/edit/FromCardList.jsx
  src/data/editPage.js
  src/pages/EditPage.jsx
  src/styles/theme.js
  src/utils/date.js
Labels: enhancement

#67 feat: axios 및 instance 추가
  package-lock.json
  package.json
  src/api/index.js
  src/api/recipient.js
  src/api/test.txt
  src/components/commons/Profile.jsx
  src/components/commons/cards/CardMessage.jsx
  src/components/commons/cards/Date.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/edit/CardContainer.jsx
  src/components/edit/EditContainer.jsx
  src/components/edit/FromCard.jsx
  src/data/editPage.js
  src/utils/constants/API.js
Labels: documentation, enhancement

#68 [#15] feat: 랜딩페이지, button 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  package-lock.json
  package.json
  public/index.html
  src/api/index.js
  src/api/recipient.js
  src/api/test.txt
  src/assets/backgrounds/nation1.svg
  src/assets/backgrounds/nation2.svg
  src/assets/images/buttons/check.svg
  src/components/commons/Profile.jsx
  src/components/commons/badges/EmojiBadge.jsx
  src/components/commons/badges/ProfileBadge.jsx
  src/components/commons/buttons/ArrowBtns.jsx
  src/components/commons/buttons/Button.jsx
  src/components/commons/buttons/DeleteBtn.jsx
  src/components/commons/buttons/IconButton.jsx
  src/components/commons/buttons/OutlinedBtn.jsx
  src/components/commons/buttons/PlusBtn.jsx
  src/components/commons/buttons/PrimaryBtn.jsx
  src/components/commons/buttons/SecondaryBtn.jsx
  src/components/commons/buttons/ToggleBtn.jsx
  src/components/commons/card/test
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/components/commons/cards/CardMessage.jsx
  src/components/commons/cards/Date.jsx
  src/components/commons/cards/FromTitle.jsx
  src/components/commons/form/InputStatus.js
  src/components/commons/form/Options.jsx
  src/components/commons/form/TextFieldDropdown.jsx
  src/components/commons/form/TextFieldInput.jsx
  src/components/commons/form/TextFieldTextEditor.jsx
  src/components/commons/form/index.js
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/modal/Modal.jsx
  src/components/commons/modal/modal/Portal.jsx
  src/components/commons/modal/modal/index.js
  src/components/commons/toast/Toast.jsx
  src/components/edit/CardContainer.jsx
  src/components/edit/EditContainer.jsx
  src/components/edit/FromCard.jsx
  src/components/edit/FromCardList.jsx
  src/data/editPage.js
  src/hooks/useDeviceType.jsx
  src/pages/AddMessagePage.jsx
  src/pages/AddPostPage.jsx
  src/pages/EditPage.jsx
  src/pages/LandingPage.jsx
  src/pages/ListPage.jsx
  src/pages/MessagePage.jsx
  src/pages/PostPage.jsx
  src/styles/theme.js
  src/utils/constants/API.js
  src/utils/date.js
Labels: enhancement

#69 [#15]Feat: landing page 구현
  src/components/commons/buttons/ArrowBtns.jsx
  src/components/commons/buttons/Button.jsx
  src/components/commons/buttons/DeleteBtn.jsx
  src/components/commons/buttons/IconButton.jsx
  src/components/commons/buttons/OutlinedBtn.jsx
  src/components/commons/buttons/PlusBtn.jsx
  src/components/commons/buttons/PrimaryBtn.jsx
  src/components/commons/buttons/SecondaryBtn.jsx
  src/components/commons/buttons/ToggleBtn.jsx
  src/components/commons/cards/Date.jsx
  src/pages/LandingPage.jsx
Labels: enhancement

#72 feat: editPage data 연결
  src/api/index.js
  src/api/message.js
  src/api/recipient.js
  src/components/commons/Loader.jsx
  src/components/commons/Profile.jsx
  src/components/commons/badges/ProfileBadge.jsx
  src/components/commons/buttons/PlusBtn.jsx
  src/components/commons/cards/CardMessage.jsx
  src/components/commons/cards/Date.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/modal/Modal.jsx
  src/components/edit/AddCard.jsx
  src/components/edit/EditContainer.jsx
  src/components/edit/FromCard.jsx
  src/components/edit/FromCardList.jsx
  src/pages/EditPage.jsx
  src/pages/MessagePage.jsx
  src/styles/theme.js
  src/utils/constants/API.js
Labels: enhancement, fix

#75 [#30] feat: 페이지 전환 URL 수정 및 CardList UI 수정
  package-lock.json
  package.json
  public/index.html
  src/api/index.js
  src/api/message.js
  src/api/recipient.js
  src/assets/images/cardList/pattern_beige.png
  src/components/commons/Loader.jsx
  src/components/commons/Profile.jsx
  src/components/commons/badges/ProfileBadge.jsx
  src/components/commons/buttons/ArrowBtns.jsx
  src/components/commons/buttons/Button.jsx
  src/components/commons/buttons/DeleteBtn.jsx
  src/components/commons/buttons/IconButton.jsx
  src/components/commons/buttons/OutlinedBtn.jsx
  src/components/commons/buttons/PlusBtn.jsx
  src/components/commons/buttons/PrimaryBtn.jsx
  src/components/commons/buttons/SecondaryBtn.jsx
  src/components/commons/buttons/ToggleBtn.jsx
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/components/commons/cards/CardMessage.jsx
  src/components/commons/cards/Date.jsx
  src/components/commons/header/GNB.jsx
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/modal/Modal.jsx
  src/components/edit/AddCard.jsx
  src/components/edit/EditContainer.jsx
  src/components/edit/FromCard.jsx
  src/components/edit/FromCardList.jsx
  src/pages/EditPage.jsx
  src/pages/LandingPage.jsx
  src/pages/ListPage.jsx
  src/pages/MessagePage.jsx
  src/styles/theme.js
  src/utils/constants/API.js
Labels: fix, refactor

#76 [#30] feat: 페이지 전환 URL 수정 및 CardList UI 수정
  src/assets/images/cardList/pattern_beige.png
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/pages/ListPage.jsx
Labels: fix, refactor

#80 [#77] ErrorPage 구현
  src/App.js
  src/components/commons/buttons/Button.jsx
  src/components/commons/buttons/PlusBtn.jsx
  src/components/commons/error/Error.jsx
  src/pages/ErrorPage.jsx
  src/utils/constants/routes.js
Labels: enhancement

#81 [#77] feat: errorPage 구현
  src/App.js
  src/components/commons/buttons/Button.jsx
  src/components/commons/buttons/PlusBtn.jsx
  src/components/commons/error/Error.jsx
  src/pages/ErrorPage.jsx
  src/utils/constants/routes.js
Labels: enhancement

#82 [#77] fix: toggleBtn borderRadius 수정, 버튼 index 수정, errorPage 수정
  src/components/commons/buttons/Button.jsx
  src/components/commons/buttons/ToggleBtn.jsx
  src/pages/ErrorPage.jsx
Labels: refactor

#83 feat: editPage 데이터 연동 구현 및 삭제 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/api/message.js
  src/api/recipient.js
  src/components/commons/modal/modal/Modal.jsx
  src/components/edit/AddCard.jsx
  src/components/edit/CardContainer.jsx
  src/components/edit/FromCard.jsx
  src/components/edit/FromCardList.jsx
  src/hooks/queries/useGetEditQuery.js
  src/hooks/useCloseModal.js
  src/pages/EditPage.jsx
  src/utils/constants/API.js
  src/utils/constants/routes.js
  src/utils/deleteAlert.js
Labels: enhancement, fix, refactor

#84 [#77] fix: errorPage, btn 수정
  src/components/commons/buttons/Button.jsx
  src/components/commons/buttons/ToggleBtn.jsx
  src/pages/ErrorPage.jsx
Labels: fix

#85 feat: 커스텀 훅 이름 변경 및 backgroundImg 에러 해결, modal 리펙토링
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/modal/Modal.jsx
  src/components/edit/EditContainer.jsx
  src/components/edit/FromCard.jsx
  src/hooks/queries/useEditQuery.js
  src/pages/EditPage.jsx
Labels: enhancement, fix, refactor

#89 [#3] feat: 헤더 일부 수정
  src/components/commons/header/GNB.jsx
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
Labels: enhancement, fix

#97 [#96] refactor: 버튼 위치 수정
  src/pages/ErrorPage.jsx
  src/pages/LandingPage.jsx
Labels: refactor

#94 [#32] Feat:CleanUp
  src/components/commons/form/Options.jsx
  src/pages/PostPage.jsx
Labels: fix, refactor

#101 [#92] refactor: ListPage UI 수정 및 useQuery 훅으로 교체
  src/api/recipient.js
  src/components/commons/cardList/CardList.jsx
  src/hooks/queries/useListQuery.js
  src/pages/ListPage.jsx
Labels: enhancement, refactor

#102 [#95] feat: 무한스크롤 구현 성공
  package-lock.json
  package.json
  src/api/recipient.js
  src/hooks/queries/useEditQuery.js
  src/pages/EditPage.jsx
Labels: enhancement

#105 [#95] feat: FromCard Skeleton 구현
  src/api/reaction.js
  src/components/commons/badges/EmojiBadge.jsx
  src/components/commons/header/GNB.jsx
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/edit/FromCardList.jsx
  src/components/edit/FromCardSkeleton.jsx
  src/hooks/queries/useReactionQuery.js
  src/pages/EditPage.jsx
Labels: enhancement

#106 [#99] feat: PapersPage UI 구현
  package-lock.json
  package.json
  src/App.js
  src/api/reaction.js
  src/api/recipient.js
  src/components/commons/badges/EmojiBadge.jsx
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/components/commons/header/GNB.jsx
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/edit/FromCardList.jsx
  src/components/edit/FromCardSkeleton.jsx
  src/data/papersPage.js
  src/hooks/queries/useEditQuery.js
  src/hooks/queries/useListQuery.js
  src/hooks/queries/useReactionQuery.js
  src/pages/EditPage.jsx
  src/pages/ListPage.jsx
  src/pages/PapersPage.jsx
  src/utils/constants/routes.js
Labels: enhancement

#107 [#99] feat: PapersPage UI 구현
  src/App.js
  src/components/commons/cardList/Card.jsx
  src/data/papersPage.js
  src/pages/ListPage.jsx
  src/pages/PapersPage.jsx
  src/utils/constants/routes.js
Labels: enhancement

#109 [#99] feat: PapersPage api 연동 및 무한스크롤 구현
  src/components/commons/cardList/Card.jsx
  src/data/papersPage.js
  src/hooks/queries/usePapersQuery.js
  src/pages/PapersPage.jsx
Labels: enhancement

#110 [#99] feat: PapersPage api 연동 및 무한스크롤 구현
  src/components/commons/cardList/Card.jsx
  src/data/papersPage.js
  src/hooks/queries/usePapersQuery.js
  src/pages/PapersPage.jsx
Labels: enhancement

#115 feat: editPage subheader 이모지 데이터 연결
  .DS_Store
  package-lock.json
  package.json
  public/index.html
  src/.DS_Store
  src/components/commons/badges/ProfileBadge.jsx
  src/components/commons/cards/CardMessage.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/modal/Modal.jsx
  src/components/edit/FromCard.jsx
  src/components/edit/FromCardList.jsx
  src/hooks/queries/useEditQuery.js
  src/hooks/queries/useReactionQuery.js
  src/pages/EditPage.jsx
  src/styles/GlobalStyle.jsx
  src/utils/errorAlert.js
Labels: bug, enhancement, fix, refactor

#114 [#92] feat: PapersPage 정렬 기능 추가 및 카드 UI 수정
  src/App.js
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/hooks/queries/usePapersQuery.js
  src/pages/ListPage.jsx
  src/pages/PapersPage.jsx
Labels: enhancement, refactor

#98 [#96] chore: 버튼 또 수정
  package-lock.json
  package.json
  src/App.js
  src/api/reaction.js
  src/api/recipient.js
  src/components/commons/badges/EmojiBadge.jsx
  src/components/commons/buttons/PrimaryBtn.jsx
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/components/commons/form/Options.jsx
  src/components/commons/header/GNB.jsx
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/edit/FromCardList.jsx
  src/components/edit/FromCardSkeleton.jsx
  src/data/papersPage.js
  src/hooks/queries/useEditQuery.js
  src/hooks/queries/useListQuery.js
  src/hooks/queries/useReactionQuery.js
  src/pages/EditPage.jsx
  src/pages/ErrorPage.jsx
  src/pages/LandingPage.jsx
  src/pages/ListPage.jsx
  src/pages/PapersPage.jsx
  src/pages/PostPage.jsx
  src/utils/constants/routes.js
Labels: refactor

#118 [#96] refactor: error page
  src/components/commons/buttons/PrimaryBtn.jsx
  src/pages/ErrorPage.jsx
  src/pages/LandingPage.jsx
Labels: refactor

#119 refactor: jsdoc 추가 및 query hook 폴더 변경
  src/.DS_Store
  src/components/commons/Profile.jsx
  src/components/commons/badges/EmojiBadge.jsx
  src/components/commons/badges/ProfileBadge.jsx
  src/components/commons/cards/CardMessage.jsx
  src/components/commons/cards/Date.jsx
  src/components/commons/cards/FromTitle.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/modal/Modal.jsx
  src/components/commons/toast/Toast.jsx
  src/components/edit/AddCard.jsx
  src/components/edit/FromCard.jsx
  src/components/edit/FromCardList.jsx
  src/data/editPage.js
  src/hooks/queries/edit/useDeleteMessageQuery.js
  src/hooks/queries/edit/useDeleteRecipientQuery.js
  src/hooks/queries/edit/useGetMessagesQuery.js
  src/hooks/queries/edit/useGetRecipientQuery.js
  src/hooks/queries/reaction/useGetReactionQuery.js
  src/hooks/queries/reaction/usePostReactionQuery.js
  src/hooks/queries/useEditQuery.js
  src/pages/EditPage.jsx
Labels: documentation, refactor

#120 [#117] chore: api 함수 jsdoc 추가
  src/.DS_Store
  src/api/message.js
  src/api/reaction.js
  src/api/recipient.js
  src/hooks/queries/edit/useDeleteMessageQuery.js
  src/hooks/queries/edit/useDeleteRecipientQuery.js
  src/hooks/queries/edit/useGetMessagesQuery.js
  src/hooks/queries/edit/useGetRecipientQuery.js
  src/hooks/queries/reaction/useGetReactionQuery.js
  src/hooks/queries/reaction/usePostReactionQuery.js
  src/styles/.DS_Store
Labels: documentation

#125 fix: emoji post api 에러 해결 및 subHeader 리팩토링
  src/components/commons/badges/EmojiBadge.jsx
  src/components/commons/header/ButtonContainer.jsx
  src/components/commons/header/Share.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/commons/header/TopEmoji.jsx
  src/hooks/queries/reaction/usePostReactionQuery.js
Labels: enhancement, fix, refactor

#124 [#92] refactor: 컴포넌트 분리 및 JSDoc 작성, 에러 모달 적용
  src/components/commons/cardList/ArrowButton.jsx
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/components/list/Footer.jsx
  src/components/list/ListName.jsx
  src/components/list/ListPageMainContainer.jsx
  src/components/list/PageChangeButton.jsx
  src/components/papers/PaperPageCard.jsx
  src/components/papers/PapersContainer.jsx
  src/components/papers/PapersPageMainContainer.jsx
  src/hooks/queries/useListQuery.js
  src/hooks/queries/usePapersQuery.js
  src/hooks/useDeviceType.js
  src/pages/ListPage.jsx
  src/pages/PapersPage.jsx
Labels: documentation, fix, refactor

#122 [#32]Feat: cleanup & refactoring
  src/api/recipient.js
  src/components/commons/form/CreateListItem.jsx
  src/components/commons/form/Options.jsx
  src/components/commons/form/TextFieldDropdown.jsx
  src/components/commons/form/TextFieldInput.jsx
  src/components/commons/form/TextFieldTextEditor.jsx
  src/pages/MessagePage.jsx
  src/pages/PostPage.jsx
Labels: refactor

#132 [#92] refactor: Card, CardList 컴포넌트 리팩토링
  src/assets/images/cardList/tempImg.jpg
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/components/papers/PapersContainer.jsx
  src/hooks/queries/list/useListQuery.js
  src/hooks/queries/papers/usePapersQuery.js
  src/pages/ListPage.jsx
  src/pages/PapersPage.jsx
Labels: refactor

#136 refactor: postPage api useQuery&useMutation 사용해서 변경
  src/api/backgroundImage.js
  src/api/profileImage.js
  src/hooks/queries/post/useGetBackgroundImageQuery.js
  src/hooks/queries/post/useGetProfileImageQuery.js
  src/hooks/queries/post/usePostMessagesQuery.js
  src/hooks/queries/post/usePostRecipientQuery.js
  src/pages/MessagePage.jsx
  src/pages/PostPage.jsx
  src/utils/infoAlert.js
Labels: enhancement, fix, refactor

#137 feat: 롤링페이퍼가 존재하지 않을 경우 nullcard component 추가
  src/App.js
  src/components/edit/FromCardList.jsx
  src/components/edit/NullCard.jsx
Labels: enhancement, refactor

#143 [#92] fix: Card 컴포넌트 EmojiBadge 수정
  src/components/commons/cardList/Card.jsx
Labels: fix

#144 fix: error 수정
  src/components/commons/cardList/Card.jsx
  src/components/commons/header/HeaderAssets/TopEmoji.jsx
Labels: documentation, fix, refactor

#145 feat: favicon 추가
  public/.DS_Store
  public/favicon.ico
  public/images/.DS_Store
  public/index.html
Labels: documentation

#153 refactor: mobile 모달 생성, 백그라운드 스크롤 막기
  src/api/index.js
  src/components/commons/cards/CardMessage.jsx
  src/components/commons/modal/modal/Modal.jsx
  src/components/edit/FromCard.jsx
  src/components/edit/FromCardList.jsx
  src/components/edit/NullCard.jsx
  src/hooks/queries/edit/useDeleteMessageQuery.js
  src/index.js
  src/pages/EditPage.jsx
Labels: enhancement, fix, refactor

#155 [#92] fix: 캐러셀 사용성 개선, PapersPage Loader 위치 변경
  src/components/commons/cardList/CardList.jsx
  src/pages/PapersPage.jsx
Labels: fix

#156 feat: font 추가 및 버그 해결
  public/.DS_Store
  public/_redirects
  public/fonts/.DS_Store
  public/index.html
  src/api/index.js
  src/components/commons/cardList/CardList.jsx
  src/components/commons/cards/CardMessage.jsx
  src/components/commons/form/CreateListItem.jsx
  src/components/commons/form/TextFieldDropdown.jsx
  src/components/commons/form/TextFieldTextEditor.jsx
  src/components/commons/header/HeaderAssets/TopEmoji.jsx
  src/components/commons/header/HeaderButton/ShareButton.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/commons/modal/modal/Modal.jsx
  src/components/edit/FromCard.jsx
  src/components/edit/FromCardList.jsx
  src/components/edit/NullCard.jsx
  src/hooks/queries/edit/useDeleteMessageQuery.js
  src/index.js
  src/pages/EditPage.jsx
  src/pages/MessagePage.jsx
  src/pages/PapersPage.jsx
  src/pages/PostPage.jsx
  src/styles/GlobalStyle.jsx
  src/utils/alert.js
  src/utils/infoAlert.js
Labels: enhancement, fix, refactor
