Repository mun-jihye/rolling-paper-app, pull requests merged in 2024-02, with the labels that each got.

#7 feat: CardList 초기 설정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  docs/pull_request_template.md
  src/components/assets/images/pattern_blue.png
  src/components/assets/images/pattern_green.png
  src/components/assets/images/pattern_orange.png
  src/components/assets/images/pattern_purple.png
  src/components/commons/cardList/CardList.jsx
  src/components/commons/cardList/test
  src/components/pages/CardLIstPage.jsx
Labels: enhancement

#8 feat: CardList 초기 설정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  docs/pull_request_template.md
  src/components/assets/images/pattern_blue.png
  src/components/assets/images/pattern_green.png
  src/components/assets/images/pattern_orange.png
  src/components/assets/images/pattern_purple.png
  src/components/commons/cardList/CardList.jsx
  src/components/commons/cardList/test
  src/components/pages/CardLIstPage.jsx
Labels: enhancement

#10 feat: Header component 초기 설정
  src/components/commons/header/GNB.jsx
  src/components/commons/header/Logo.svg
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/commons/header/test
  src/components/pages/CardLIstPage.jsx
  src/components/pages/Header.jsx
  src/components/styles/GlobalStyle.jsx
Labels: enhancement

#12 feat: button 초기 설정
  src/components/commons/buttons/ArrowBtn.jsx
  src/components/commons/buttons/ButtonSize.js
  src/components/commons/buttons/OutlinedBtn.jsx
  src/components/commons/buttons/PrimaryBtn.jsx
  src/components/commons/buttons/SecondaryBtn.jsx
  src/components/commons/buttons/StyledButton.jsx
  src/components/commons/buttons/ToggleBtn.jsx
  src/components/commons/buttons/test
  src/components/pages/ButtonPage.jsx
  src/components/pages/CardLIstPage.jsx
Labels: enhancement

#13 feat: 모달 초기 구현
  .DS_Store
  public/index.html
  src/.DS_Store
  src/App.js
  src/components/.DS_Store
  src/components/assets/.DS_Store
  src/components/assets/images/profiles/profile1.png
  src/components/assets/images/profiles/profile2.png
  src/components/assets/images/profiles/profile3.png
  src/components/commons/Profile.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/Modal.jsx
  src/components/commons/modal/Portal.jsx
  src/components/commons/modal/test
  src/components/hooks/test
  src/components/hooks/useCloseModal.jsx
  src/components/pages/Modal.jsx
  src/components/pages/ModalPage.jsx
Labels: enhancement

#18 [#6] feat: cardList content 디자인 및 기능 구현
  src/components/assets/images/cardList/arrow.png
  src/components/assets/images/cardList/pattern_blue.png
  src/components/assets/images/cardList/pattern_green.png
  src/components/assets/images/cardList/pattern_orange.png
  src/components/assets/images/cardList/pattern_purple.png
  src/components/assets/images/cardList/tempImg.jpg
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
  src/components/pages/CardLIstPage.jsx
Labels: enhancement, refactor

#16 [#4] feat: TextField 구현 완료
  package-lock.json
  package.json
  src/components/assets/images/icons/arrow_down.svg
  src/components/assets/images/icons/arrow_top.svg
  src/components/assets/images/icons/bold_icon.svg
  src/components/assets/images/icons/bullet.svg
  src/components/assets/images/icons/center_aligned.svg
  src/components/assets/images/icons/fill.svg
  src/components/assets/images/icons/font_size.svg
  src/components/assets/images/icons/italics.svg
  src/components/assets/images/icons/justify.svg
  src/components/assets/images/icons/numbering.svg
  src/components/assets/images/icons/right_aligned.svg
  src/components/assets/images/icons/under_score.svg
  src/components/commons/form/CreateListItem.jsx
  src/components/commons/form/DropDownStatus.js
  src/components/commons/form/Dropdown.jsx
  src/components/commons/form/InputStatus.js
  src/components/commons/form/TextFieldDropdown.jsx
  src/components/commons/form/TextFieldInput.jsx
  src/components/commons/form/TextFieldTextEditor.jsx
  src/components/commons/form/index.js
  src/components/commons/form/test
  src/components/pages/FormPage.jsx
Labels: enhancement, refactor

#19 [#3] feat: 헤더 컴포넌트 구현
  src/components/assets/images/headers/AddImage.svg
  src/components/assets/images/headers/ArrowDown.svg
  src/components/assets/images/headers/Logo.svg
  src/components/assets/images/headers/ShareImage.svg
  src/components/commons/header/GNB.jsx
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/utils/constants/routes.js
Labels: enhancement

#31 Feat component badge
  src/components/commons/badges/EmojiBadge.jsx
  src/components/commons/badges/ProfileBadge.jsx
  src/components/pages/EditPage.jsx
  src/components/pages/ModalPage.jsx
Labels: enhancement

#34 [#6] feat: cardList 컴포넌트 구현 완료
  package-lock.json
  package.json
  src/components/assets/images/buttons/arrowLeft.png
  src/components/assets/images/buttons/arrowRight.png
  src/components/assets/images/buttons/check.png
  src/components/assets/images/buttons/delete.png
  src/components/assets/images/buttons/down.png
  src/components/assets/images/buttons/edit.png
  src/components/assets/images/buttons/emoji.png
  src/components/assets/images/buttons/emojiMobile.png
  src/components/assets/images/buttons/plus.png
  src/components/assets/images/buttons/share.png
  src/components/assets/images/buttons/shareMobile.png
  src/components/assets/images/headers/AddImage.svg
  src/components/assets/images/headers/ArrowDown.svg
  src/components/assets/images/headers/Logo.svg
  src/components/assets/images/headers/ShareImage.svg
  src/components/assets/images/icons/arrow_down.svg
  src/components/assets/images/icons/arrow_top.svg
  src/components/assets/images/icons/bold_icon.svg
  src/components/assets/images/icons/bullet.svg
  src/components/assets/images/icons/center_aligned.svg
  src/components/assets/images/icons/fill.svg
  src/components/assets/images/icons/font_size.svg
  src/components/assets/images/icons/italics.svg
  src/components/assets/images/icons/justify.svg
  src/components/assets/images/icons/numbering.svg
  src/components/assets/images/icons/right_aligned.svg
  src/components/assets/images/icons/under_score.svg
  src/components/commons/buttons/ArrowBtn.jsx
  src/components/commons/buttons/ArrowBtns.jsx
  src/components/commons/buttons/ButtonSize.js
  src/components/commons/buttons/DeleteBtn.jsx
  src/components/commons/buttons/OutlinedBtn.jsx
  src/components/commons/buttons/PlusBtn.jsx
  src/components/commons/buttons/PrimaryBtn.jsx
  src/components/commons/buttons/SecondaryBtn.jsx
  src/components/commons/buttons/StyledButton.jsx
  src/components/commons/buttons/ToggleBtn.jsx
  src/components/commons/cardList/CardList.jsx
  src/components/commons/form/CreateListItem.jsx
  src/components/commons/form/DropDownStatus.js
  src/components/commons/form/Dropdown.jsx
  src/components/commons/form/InputStatus.js
  src/components/commons/form/TextFieldDropdown.jsx
  src/components/commons/form/TextFieldInput.jsx
  src/components/commons/form/TextFieldTextEditor.jsx
  src/components/commons/form/index.js
  src/components/commons/form/test
  src/components/commons/header/GNB.jsx
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/Modal.jsx
  src/components/pages/ButtonPage.jsx
  src/components/pages/FormPage.jsx
  src/components/styles/theme.js
  src/components/utils/constants/routes.js
Labels: enhancement, fix

#37 [#33] feat: toast component 구조 잡기
  src/components/assets/images/toast/completed.png
  src/components/commons/toast/Animation.js
  src/components/commons/toast/Toast.jsx
  src/components/pages/EditPage.jsx
  src/components/styles/GlobalStyle.jsx
Labels: enhancement

#41 [#30] feat: ListPage 초기 설계
  src/components/pages/ButtonPage.jsx
  src/components/pages/CardLIstPage.jsx
  src/components/pages/FormPage.jsx
  src/components/pages/Header.jsx
  src/components/pages/ListPage.jsx
Labels: enhancement

#51 fix: 파일 경로 수정
  public/index.html
  src/components/commons/modal/CardModal.jsx
  src/components/commons/modal/Modal.jsx
  src/components/commons/toast/Toast.jsx
Labels: fix

#52 [#30] fix: card, cardList 폴더 경로 수정
  src/components/commons/cardList/Card.jsx
  src/components/commons/cardList/CardList.jsx
Labels: fix

#53 [#3] fix: 헤더 페이지 내 경로 수정
  src/components/commons/header/MainHeader.jsx
  src/components/commons/header/SubHeader.jsx
Labels: fix

#58 feat: Toast component 구현 완료
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  package-lock.json
  package.json
  src/components/commons/toast/Toast.jsx
  src/pages/EditPage.jsx
Labels: enhancement
